(()=>{'use strict';
const reduced=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
const coarse=window.matchMedia?.('(pointer: coarse)').matches;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const style=document.createElement('style');
style.textContent=`
/* NOVA AWARD LAYER. Additive only. */
.nova-field{position:fixed;inset:0;z-index:0;pointer-events:none;overflow:hidden;opacity:.8}.nova-field i{position:absolute;width:1px;height:1px;background:var(--ice);box-shadow:0 0 18px 2px var(--ice);border-radius:50%;opacity:.22;transform:translate(-50%,-50%);transition:opacity .4s}.nova-field .field-core{width:28vw;height:28vw;border:1px solid rgba(143,236,230,.08);border-radius:50%;filter:blur(.2px);transform:translate(-50%,-50%);transition:width .7s ease,height .7s ease,opacity .5s ease}.award-progress{position:fixed;left:0;top:0;width:100%;height:2px;z-index:1101;transform-origin:left;background:var(--ice);box-shadow:0 0 16px rgba(143,236,230,.45);transform:scaleX(0);pointer-events:none}.project{transform-style:preserve-3d}.project .project-main{position:relative;z-index:1}.project:after{content:'';position:absolute;inset:0;pointer-events:none;border:1px solid transparent;transition:border-color .3s,box-shadow .3s}.project:hover:after{border-color:rgba(143,236,230,.18);box-shadow:inset 0 0 70px rgba(143,236,230,.025)}.project-main h3{transition:letter-spacing .5s ease,transform .5s ease}.project:hover .project-main h3{letter-spacing:.015em;transform:translateX(4px)}.nova-field-label{position:fixed;left:24px;bottom:24px;z-index:80;font:7px var(--mono);letter-spacing:.15em;color:var(--muted);pointer-events:none;opacity:.5}.nova-field-label b{color:var(--ice);font-weight:400}.contact{position:relative;overflow:hidden}.contact:before{content:'NOVA';position:absolute;right:-.05em;bottom:-.22em;font:800 30vw/.7 var(--display);letter-spacing:-.08em;color:rgba(255,255,255,.018);pointer-events:none}.contact .wrap{position:relative;z-index:1}.hero-copy,.hero-frame{will-change:transform}.button,.project-footer a,.contact-links a{will-change:transform}.award-focus{outline:1px solid var(--ice);outline-offset:7px}@media(max-width:900px){.nova-field-label{display:none}.award-progress{height:1px}.contact:before{font-size:42vw}}
@media(prefers-reduced-motion:reduce){.nova-field{display:none}.project{transform:none!important}}
.portrait-photo-local{position:absolute;left:50%;top:50%;width:76%;height:76%;transform:translate(-50%,-50%);z-index:3;border-radius:0;overflow:hidden;border:1px solid rgba(143,236,230,.28);background:#08090b;box-shadow:0 0 42px rgba(143,236,230,.14)}.portrait-photo-local img{width:100%;height:100%;object-fit:cover;object-position:center top;display:block;filter:saturate(.92) contrast(1.04)}.portrait-photo-local:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,transparent 58%,rgba(8,9,11,.25));pointer-events:none}.portrait-art .portrait-mark{z-index:1!important;opacity:.3}
@media(max-width:900px){.portrait-photo-local{width:78%;height:78%}}
.nova-about-expanded{margin-top:22px}.nova-about-expanded p{max-width:760px;margin:0 0 18px;color:var(--muted);font:400 14px/1.8 var(--sans)}.nova-about-expanded p:first-child{color:var(--fg)}.nova-about-expanded .about-kicker{font:7px var(--mono);letter-spacing:.16em;color:var(--ice);text-transform:uppercase;margin-bottom:8px}.nova-about-panels{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:24px}.nova-about-panel{border-top:1px solid var(--line);padding-top:12px}.nova-about-panel span{display:block;font:7px var(--mono);letter-spacing:.13em;color:var(--muted);text-transform:uppercase;margin-bottom:8px}.nova-about-panel b{display:block;font:500 11px/1.7 var(--mono);color:var(--fg)}
@media(max-width:900px){.nova-about-panels{grid-template-columns:1fr}.nova-about-expanded p{font-size:13px}}
.nova-client-work{margin-top:38px}.nova-client-head{display:flex;justify-content:space-between;align-items:flex-end;gap:28px;margin:0 0 24px}.nova-client-head h3{font:700 clamp(30px,4vw,52px)/.95 var(--display);letter-spacing:-.03em}.nova-client-head p{max-width:42ch;color:var(--muted);font-size:13px;line-height:1.6}.nova-client-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.nova-client-card{position:relative;overflow:hidden;border:1px solid var(--line);background:linear-gradient(145deg,#101216,#090a0c);padding:28px;min-height:280px;display:flex;flex-direction:column;justify-content:space-between;transition:transform .35s ease,border-color .25s ease,background .35s ease}.nova-client-card:before{content:'';position:absolute;inset:0;background:radial-gradient(circle at 85% 10%,rgba(143,236,230,.09),transparent 42%);pointer-events:none}.nova-client-card:hover{border-color:rgba(143,236,230,.38);background:linear-gradient(145deg,#11161a,#090a0c)}.nova-client-card .client-index{font:8px var(--mono);letter-spacing:.14em;color:var(--ice)}.nova-client-card h4{position:relative;margin-top:28px;font:700 clamp(30px,4vw,52px)/.9 var(--display);letter-spacing:-.035em}.nova-client-card p{position:relative;margin-top:14px;max-width:38ch;color:var(--muted);font-size:12px;line-height:1.65}.nova-client-card .client-tags{position:relative;display:flex;flex-wrap:wrap;gap:7px;margin-top:18px}.nova-client-card .client-tags span{padding:5px 8px;border:1px solid var(--line);border-radius:999px;font:7px var(--mono);letter-spacing:.1em;text-transform:uppercase;color:var(--muted)}.nova-client-card a{position:relative;display:inline-flex;align-items:center;gap:8px;margin-top:24px;width:max-content;padding:10px 14px;border:1px solid var(--line);border-radius:999px;font:8px var(--mono);letter-spacing:.11em;text-transform:uppercase;transition:border-color .2s,background .2s}.nova-client-card a:hover{border-color:var(--ice);background:rgba(143,236,230,.07)}.nova-client-footer{margin-top:15px;font:7px var(--mono);letter-spacing:.12em;text-transform:uppercase;color:var(--muted)}
@media(max-width:700px){.nova-client-head{display:block}.nova-client-head p{margin-top:12px}.nova-client-grid{grid-template-columns:1fr}.nova-client-card{min-height:250px;padding:24px}}
`;
document.head.appendChild(style);
const progress=document.createElement('div');progress.className='award-progress';document.body.appendChild(progress);
const field=document.createElement('div');field.className='nova-field';field.setAttribute('aria-hidden','true');document.body.appendChild(field);
const core=document.createElement('span');core.className='field-core';field.appendChild(core);
const dots=[];for(let i=0;i<22;i++){const d=document.createElement('i');field.appendChild(d);dots.push({el:d,x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.16,vy:(Math.random()-.5)*.16,seed:Math.random()*10});}
const label=document.createElement('div');label.className='nova-field-label';label.innerHTML='FIELD / <b>ACTIVE</b>';document.body.appendChild(label);
let mx=innerWidth*.5,my=innerHeight*.5,fx=mx,fy=my,scrollVelocity=0,lastScroll=scrollY,lastTime=performance.now();
addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY},{passive:true});
addEventListener('resize',()=>{dots.forEach(d=>{d.x=Math.min(d.x,innerWidth);d.y=Math.min(d.y,innerHeight)})});
function frame(t){const dt=Math.min(32,t-lastTime);lastTime=t;fx+=(mx-fx)*.045;fy+=(my-fy)*.045;if(!coarse&&!reduced){core.style.left=fx+'px';core.style.top=fy+'px';const intensity=Math.min(1,Math.abs(scrollVelocity)*1.5);core.style.width=`${28+intensity*8}vw`;core.style.height=`${28+intensity*8}vw`;dots.forEach(d=>{const dx=mx-d.x,dy=my-d.y,dist=Math.hypot(dx,dy),pull=Math.max(0,1-dist/320);d.vx+=(dx/(dist||1))*.002*pull;d.vy+=(dy/(dist||1))*.002*pull;d.vx*=.995;d.vy*=.995;d.x+=d.vx*dt;d.y+=d.vy*dt;if(d.x<0||d.x>innerWidth)d.vx*=-1;if(d.y<0||d.y>innerHeight)d.vy*=-1;d.el.style.left=d.x+'px';d.el.style.top=d.y+'px';d.el.style.opacity=.08+pull*.5;d.el.style.transform=`translate(-50%,-50%) scale(${1+pull*3})`})}requestAnimationFrame(frame)}requestAnimationFrame(frame);
addEventListener('scroll',()=>{const now=performance.now();scrollVelocity=(scrollY-lastScroll)/Math.max(16,now-lastTime);lastScroll=scrollY;progress.style.transform=`scaleX(${Math.min(1,Math.max(0,scrollY/(document.documentElement.scrollHeight-innerHeight)))})`},{passive:true});
if(!coarse&&!reduced){$$('.project').forEach(card=>{card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(1400px) rotateX(${(-y*2.2).toFixed(2)}deg) rotateY(${(x*2.2).toFixed(2)}deg) translateZ(0)`});card.addEventListener('mouseleave',()=>card.style.transform='')});const frameEl=$('#heroFrame');if(frameEl){addEventListener('mousemove',e=>{const r=frameEl.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;frameEl.style.setProperty('--mx',`${x*100}%`);frameEl.style.setProperty('--my',`${y*100}%`)},{passive:true})}}
const anchors=$$('a,button');anchors.forEach(el=>{el.addEventListener('focus',()=>el.classList.add('award-focus'));el.addEventListener('blur',()=>el.classList.remove('award-focus'))});
const sections=$$('section[id]');if('IntersectionObserver'in window){const ob=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.style.setProperty('--section-progress',Math.min(1,Math.max(0,(innerHeight-e.boundingClientRect.top)/(innerHeight+e.boundingClientRect.height))))}),{threshold:[0,.25,.5,.75,1]});sections.forEach(s=>ob.observe(s))}
const portraitArt=$('.portrait-art');if(portraitArt&&!portraitArt.querySelector('.portrait-photo-local')){const wrap=document.createElement('div');wrap.className='portrait-photo-local';const img=document.createElement('img');img.src='assets/oshan.jpg';img.alt='Oshan Tanusha';img.loading='eager';img.decoding='async';wrap.appendChild(img);portraitArt.appendChild(wrap)}
const about=$('#about .about-grid');if(about&&!about.querySelector('.nova-about-expanded')){const first=about.firstElementChild;const box=document.createElement('div');box.className='nova-about-expanded';box.innerHTML=`<p class="about-kicker">The person behind NOVA</p><p>I’m Oshan Tanusha, the person behind NOVA. I’m a software engineering student from Sri Lanka, focused on building digital experiences and physical interactive systems.</p><p>My work sits between software, interaction design, embedded systems, and creative technology. I like taking an idea from a screen, turning it into something people interact with, then refining the details until the experience feels intentional.</p><p>BLVND explores digital identity and web interaction. NYX explores physical interaction through sensors, movement, expression, and rule-based behavior. Each project gives me a different problem to solve and a different way to learn.</p><p>My future direction is iOS development. I want to build polished mobile experiences and grow deeper into Apple’s ecosystem while continuing to explore interactive technology. Alongside software, I’m also exploring music production, another creative side of NOVA where technology, sound, and experimentation meet.</p><div class="nova-about-panels"><div class="nova-about-panel"><span>NOW</span><b>Software engineering<br>Web + embedded systems</b></div><div class="nova-about-panel"><span>NEXT</span><b>iOS development<br>Mobile interaction</b></div><div class="nova-about-panel"><span>ALSO EXPLORING</span><b>Music production<br>Sound + creative technology</b></div></div>`;first.appendChild(box)}
const work=$('#work');
if(work&&!work.querySelector('.nova-client-work')){
 const wrap=work.querySelector('.wrap');
 const section=document.createElement('div');
 section.className='nova-client-work reveal in';
 section.innerHTML=`<div class="nova-client-head"><div><p class="eyebrow">02 / Client demos</p><h3>Built for real businesses.</h3></div><p>Website concepts created to solve practical presentation, booking, and customer experience problems for local businesses.</p></div><div class="nova-client-grid"><article class="nova-client-card"><div><span class="client-index">01 / OLU SPA</span><h4>OLU SPA</h4><p>A focused spa website concept for presenting services, pricing, contact details, and a cleaner customer journey.</p><div class="client-tags"><span>Web design</span><span>Responsive</span><span>Business demo</span></div></div><div><a href="https://alphaoshyy.github.io/olu-spa-galle/" target="_blank" rel="noopener" data-cursor="LIVE">View live demo ↗</a><div class="nova-client-footer">Demo / Galle</div></div></article><article class="nova-client-card"><div><span class="client-index">02 / Pearl View</span><h4>PEARL VIEW</h4><p>A villa website concept focused on presenting rooms, facilities, location, and direct enquiry information clearly.</p><div class="client-tags"><span>Hospitality</span><span>UI design</span><span>Responsive</span></div></div><div><a href="https://alphaoshyy.github.io/Pearl-View-Galle-VillA/" target="_blank" rel="noopener" data-cursor="LIVE">View live demo ↗</a><div class="nova-client-footer">Demo / Galle</div></div></article><article class="nova-client-card"><div><span class="client-index">03 / Coco & Date</span><h4>COCO &amp; DATE</h4><p>A business website concept built to give a local brand a stronger digital presence and clearer customer navigation.</p><div class="client-tags"><span>Brand site</span><span>Web design</span><span>Demo</span></div></div><div><a href="https://alphaoshyy.github.io/coco-date-website/" target="_blank" rel="noopener" data-cursor="LIVE">View live demo ↗</a><div class="nova-client-footer">Demo / Sri Lanka</div></div></article><article class="nova-client-card"><div><span class="client-index">04 / Nomads Colive</span><h4>NOMADS COLIVE</h4><p>A coliving website concept focused on accommodation, location, amenities, and a direct enquiry path.</p><div class="client-tags"><span>Hospitality</span><span>Responsive</span><span>UX</span></div></div><div><a href="https://alphaoshyy.github.io/nomads-colive-koggala-demo/" target="_blank" rel="noopener" data-cursor="LIVE">View live demo ↗</a><div class="nova-client-footer">Demo / Koggala</div></div></article></div>`;
 wrap.appendChild(section);
}
const contactLinks=$$('.contact-links a');contactLinks.forEach(a=>{const text=(a.textContent||'').toLowerCase();const href=(a.getAttribute('href')||'').toLowerCase();if(text.includes('linkedin')||href.includes('linkedin')){a.href='https://lk.linkedin.com/in/oshan-tanusha-661906356';a.target='_blank';a.rel='noopener'}if(text.includes('email')||text.includes('mail')||href.startsWith('mailto:')){a.href='mailto:tanushaoshyy@gmail.com';}});
})();