(()=>{'use strict';
const reduced=window.matchMedia?.('(prefers-reduced-motion: reduce)').matches;
const coarse=window.matchMedia?.('(pointer: coarse)').matches;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const style=document.createElement('style');
style.textContent=`
/* NOVA AWARD LAYER. Additive only. */
.nova-field{position:fixed;inset:0;z-index:0;pointer-events:none;overflow:hidden;opacity:.8}.nova-field i{position:absolute;width:1px;height:1px;background:var(--ice);box-shadow:0 0 18px 2px var(--ice);border-radius:50%;opacity:.22;transform:translate(-50%,-50%);transition:opacity .4s}.nova-field .field-core{width:28vw;height:28vw;border:1px solid rgba(143,236,230,.08);border-radius:50%;filter:blur(.2px);transform:translate(-50%,-50%);transition:width .7s ease,height .7s ease,opacity .5s ease}.award-progress{position:fixed;left:0;top:0;width:100%;height:2px;z-index:1101;transform-origin:left;background:var(--ice);box-shadow:0 0 16px rgba(143,236,230,.45);transform:scaleX(0);pointer-events:none}.project{transform-style:preserve-3d}.project .project-main{position:relative;z-index:1}.project:after{content:'';position:absolute;inset:0;pointer-events:none;border:1px solid transparent;transition:border-color .3s,box-shadow .3s}.project:hover:after{border-color:rgba(143,236,230,.18);box-shadow:inset 0 0 70px rgba(143,236,230,.025)}.project-main h3{transition:letter-spacing .5s ease,transform .5s ease}.project:hover .project-main h3{letter-spacing:.015em;transform:translateX(4px)}.nova-field-label{position:fixed;left:24px;bottom:24px;z-index:80;font:7px var(--mono);letter-spacing:.15em;color:var(--muted);pointer-events:none;opacity:.5}.nova-field-label b{color:var(--ice);font-weight:400}.contact{position:relative;overflow:hidden}.contact:before{content:'NOVA';position:absolute;right:-.05em;bottom:-.22em;font:800 30vw/.7 var(--display);letter-spacing:-.08em;color:rgba(255,255,255,.018);pointer-events:none}.contact .wrap{position:relative;z-index:1}.hero-copy,.hero-frame{will-change:transform}.button,.project-footer a,.contact-links a{will-change:transform}.award-focus{outline:1px solid var(--ice);outline-offset:7px}
/* LOCAL PORTRAIT. The N stays behind the photo. */
.portrait-photo-local{position:absolute;left:50%;top:42%;width:48%;aspect-ratio:1;transform:translate(-50%,-50%);z-index:3;border-radius:50%;overflow:hidden;border:1px solid rgba(143,236,230,.28);background:#08090b;box-shadow:0 0 42px rgba(143,236,230,.14)}.portrait-photo-local img{width:100%;height:100%;object-fit:cover;object-position:center top;display:block;filter:saturate(.92) contrast(1.04)}.portrait-photo-local:after{content:'';position:absolute;inset:0;background:linear-gradient(180deg,transparent 58%,rgba(8,9,11,.25));pointer-events:none}.portrait-art .portrait-mark{z-index:1!important;opacity:.3}
@media(max-width:900px){.nova-field-label{display:none}.award-progress{height:1px}.contact:before{font-size:42vw}.portrait-photo-local{width:52%}}
@media(prefers-reduced-motion:reduce){.nova-field{display:none}.project{transform:none!important}}
`;
document.head.appendChild(style);
const progress=document.createElement('div');progress.className='award-progress';document.body.appendChild(progress);
const field=document.createElement('div');field.className='nova-field';field.setAttribute('aria-hidden','true');document.body.appendChild(field);
const core=document.createElement('span');core.className='field-core';field.appendChild(core);
const dots=[];for(let i=0;i<22;i++){const d=document.createElement('i');field.appendChild(d);dots.push({el:d,x:Math.random()*innerWidth,y:Math.random()*innerHeight,vx:(Math.random()-.5)*.16,vy:(Math.random()-.5)*.16,seed:Math.random()*10});}
const label=document.createElement('div');label.className='nova-field-label';label.innerHTML='FIELD / <b>ACTIVE</b>';document.body.appendChild(label);
let mx=innerWidth*.5,my=innerHeight*.5,fx=mx,fy=my,scrollVelocity=0,lastScroll=scrollY,lastTime=performance.now();
addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY},{passive:true});
addEventListener('resize',()=>{dots.forEach(d=>{d.x=Math.min(d.x,innerWidth);d.y=Math.min(d.y,innerHeight)})});
function frame(t){const dt=Math.min(32,t-lastTime);lastTime=t;fx+=(mx-fx)*.045;fy+=(my-fy)*.045;if(!coarse&&!reduced){core.style.left=fx+'px';core.style.top=fy+'px';const intensity=Math.min(1,Math.abs(scrollVelocity)*1.5);core.style.width=`${28+intensity*8}vw`;core.style.height=`${28+intensity*8}vw`;dots.forEach((d,i)=>{const dx=mx-d.x,dy=my-d.y,dist=Math.hypot(dx,dy),pull=Math.max(0,1-dist/320);d.vx+=(dx/(dist||1))*.002*pull;d.vy+=(dy/(dist||1))*.002*pull;d.vx*=.995;d.vy*=.995;d.x+=d.vx*dt;d.y+=d.vy*dt;if(d.x<0||d.x>innerWidth)d.vx*=-1;if(d.y<0||d.y>innerHeight)d.vy*=-1;d.el.style.left=d.x+'px';d.el.style.top=d.y+'px';d.el.style.opacity=.08+pull*.5;d.el.style.transform=`translate(-50%,-50%) scale(${1+pull*3})`})}requestAnimationFrame(frame)}requestAnimationFrame(frame);
addEventListener('scroll',()=>{const now=performance.now(),dt=Math.max(16,now-lastTime);scrollVelocity=(scrollY-lastScroll)/dt;lastScroll=scrollY;progress.style.transform=`scaleX(${Math.min(1,Math.max(0,scrollY/(document.documentElement.scrollHeight-innerHeight)))})`},{passive:true});
if(!coarse&&!reduced){$$('.project').forEach(card=>{card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(1400px) rotateX(${(-y*2.2).toFixed(2)}deg) rotateY(${(x*2.2).toFixed(2)}deg) translateZ(0)`});card.addEventListener('mouseleave',()=>card.style.transform='')});const frameEl=$('#heroFrame');if(frameEl){addEventListener('mousemove',e=>{const r=frameEl.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;frameEl.style.setProperty('--mx',`${x*100}%`);frameEl.style.setProperty('--my',`${y*100}%`)},{passive:true})}}
const anchors=$$('a,button');anchors.forEach(el=>{el.addEventListener('focus',()=>el.classList.add('award-focus'));el.addEventListener('blur',()=>el.classList.remove('award-focus'))});
const sections=$$('section[id]');if('IntersectionObserver'in window){const ob=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.style.setProperty('--section-progress',Math.min(1,Math.max(0,(innerHeight-e.boundingClientRect.top)/(innerHeight+e.boundingClientRect.height))))}),{threshold:[0,.25,.5,.75,1]});sections.forEach(s=>ob.observe(s))}
/* Use the repository photo. No external CDN dependency. */
const portraitArt=$('.portrait-art');if(portraitArt&&!portraitArt.querySelector('.portrait-photo-local')){const wrap=document.createElement('div');wrap.className='portrait-photo-local';const img=document.createElement('img');img.src='assets/oshan.jpg';img.alt='Oshan Tanusha';img.loading='eager';img.decoding='async';wrap.appendChild(img);portraitArt.appendChild(wrap)}
/* Remove the repeated About bio while keeping the About identity header and skill data. */
const aboutBio=$('.about-section .bio');if(aboutBio)aboutBio.remove();
})();