const cursor=document.querySelector('.cursor'),label=document.querySelector('.cursor-label'),progress=document.querySelector('.progress');
const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const lenis=reduced?null:new Lenis({duration:1.15,smoothWheel:true,syncTouch:false});
if(lenis){lenis.on('scroll',ScrollTrigger.update);gsap.ticker.add(time=>lenis.raf(time*1000));gsap.ticker.lagSmoothing(0)}
window.addEventListener('load',()=>{
 if(!reduced){gsap.registerPlugin(ScrollTrigger);const intro=gsap.timeline();intro.to('.loader-bar i',{width:'100%',duration:1.4,ease:'power3.inOut'}).to('.loader-logo',{scale:.72,opacity:0,duration:.45,ease:'power2.in'}).to('.loader',{yPercent:-100,duration:1.05,ease:'power4.inOut'},'-=.05').from('.hero-kicker',{y:20,opacity:0,duration:.6,ease:'power3.out'},'-=.45').from('.hero-center h1',{yPercent:105,duration:1.1,ease:'power4.out'},'-=.35').from('.hero-center h2',{y:35,opacity:0,duration:.8,ease:'power3.out'},'-=.65').from('.hero-bottom',{y:30,opacity:0,duration:.8,ease:'power3.out'},'-=.5');gsap.to('.hero-orb',{x:'-6vw',y:'7vh',scale:1.08,rotation:18,duration:8,repeat:-1,yoyo:true,ease:'sine.inOut'});gsap.to('.orb-two',{x:'3vw',y:'-4vh',rotation:-25,duration:11,repeat:-1,yoyo:true,ease:'sine.inOut'});document.querySelectorAll('.reveal').forEach(el=>gsap.fromTo(el,{y:80,opacity:0},{y:0,opacity:1,duration:1.1,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 78%',once:true}}));document.querySelectorAll('.case').forEach(card=>{const visual=card.querySelector('.case-visual');gsap.from(visual,{scale:.91,rotation:1.5,duration:1.2,ease:'power3.out',scrollTrigger:{trigger:card,start:'top 80%',once:true}});gsap.from(card.querySelector('.case-copy'),{x:-50,opacity:0,duration:1,ease:'power3.out',scrollTrigger:{trigger:card,start:'top 78%',once:true}})});gsap.from('.about-layout',{y:60,opacity:0,duration:1.1,ease:'power3.out',scrollTrigger:{trigger:'.about-layout',start:'top 75%',once:true}});gsap.from('.direction-title span',{x:(i)=>i%2?-90:90,opacity:0,duration:1,stagger:.1,ease:'power3.out',scrollTrigger:{trigger:'.direction-title',start:'top 78%',once:true}});gsap.from('.contact-main a',{scale:.88,opacity:0,duration:1.2,ease:'power3.out',scrollTrigger:{trigger:'.contact-main',start:'top 75%',once:true}});gsap.to('.hero-center',{y:80,opacity:.18,scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});gsap.to('.hero-orb',{y:180,scrollTrigger:{trigger:'.hero',start:'top top',end:'bottom top',scrub:1}});gsap.to('.site-frame',{y:-28,scrollTrigger:{trigger:'.blvnd',start:'top bottom',end:'bottom top',scrub:1}});gsap.to('.nyx-face',{y:-22,scale:1.06,scrollTrigger:{trigger:'.nyx',start:'top bottom',end:'bottom top',scrub:1}})}
 const update=()=>{const max=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=(max>0?scrollY/max*100:0)+'%'};window.addEventListener('scroll',update,{passive:true});update();
 if(cursor&&!reduced){let mx=innerWidth/2,my=innerHeight/2,cx=mx,cy=my;window.addEventListener('mousemove',e=>{mx=e.clientX;my=e.clientY});gsap.ticker.add(()=>{cx+=(mx-cx)*.18;cy+=(my-cy)*.18;gsap.set(cursor,{x:cx,y:cy});if(label)gsap.set(label,{x:cx,y:cy})});document.querySelectorAll('[data-cursor]').forEach(el=>{el.addEventListener('mouseenter',()=>{cursor.classList.add('active');if(label){label.textContent=el.dataset.cursor;label.style.opacity='1'}});el.addEventListener('mouseleave',()=>{cursor.classList.remove('active');if(label)label.style.opacity='0'})});document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect(),x=e.clientX-(r.left+r.width/2),y=e.clientY-(r.top+r.height/2);gsap.to(el,{x:x*.16,y:y*.16,duration:.35,ease:'power2.out'})});el.addEventListener('mouseleave',()=>gsap.to(el,{x:0,y:0,duration:.5,ease:'elastic.out(1,.4)'})});document.querySelectorAll('.case').forEach(card=>{card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;gsap.to(card,{rotationX:y*-1.4,rotationY:x*1.4,duration:.45,ease:'power2.out',transformPerspective:1400})});card.addEventListener('mouseleave',()=>gsap.to(card,{rotationX:0,rotationY:0,duration:.7,ease:'power3.out'}))})}
});
