const cursor=document.querySelector('.cursor');
const progress=document.querySelector('.progress');
const reveals=document.querySelectorAll('.reveal');
window.addEventListener('mousemove',e=>{if(cursor){cursor.style.left=e.clientX+'px';cursor.style.top=e.clientY+'px'}});
document.querySelectorAll('a,.magnetic-card').forEach(el=>{el.addEventListener('mouseenter',()=>cursor?.classList.add('active'));el.addEventListener('mouseleave',()=>cursor?.classList.remove('active'))});
const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});
reveals.forEach(el=>observer.observe(el));
const updateProgress=()=>{const max=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=(max>0?scrollY/max*100:0)+'%'};
window.addEventListener('scroll',updateProgress,{passive:true});updateProgress();
document.querySelectorAll('.magnetic').forEach(el=>{el.addEventListener('mousemove',e=>{const r=el.getBoundingClientRect();const x=(e.clientX-r.left-r.width/2)*.16;const y=(e.clientY-r.top-r.height/2)*.16;el.style.transform=`translate(${x}px,${y}px)`});el.addEventListener('mouseleave',()=>el.style.transform='')});
document.querySelectorAll('.magnetic-card').forEach(card=>{card.addEventListener('mousemove',e=>{const r=card.getBoundingClientRect();const x=(e.clientX-r.left)/r.width-.5;const y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(1400px) rotateX(${y*-1.5}deg) rotateY(${x*1.5}deg)`});card.addEventListener('mouseleave',()=>card.style.transform='')});
const hero=document.querySelector('.hero');
window.addEventListener('scroll',()=>{if(!hero||innerWidth<801)return;const y=Math.min(scrollY,innerHeight);const core=hero.querySelector('.hero-core');const glow=hero.querySelector('.hero-glow');if(core)core.style.transform=`translateY(${y*.12}px)`;if(glow)glow.style.transform=`translate3d(${y*.015}px,${y*.04}px,0)`},{passive:true});
